FROM openjdk:8-jdk-alpine
 
VOLUME /tmp
 
ENV DATABASE_HOST=host.docker.internal
ENV DATABASE_PORT=3306
ENV DATABASE_NAME=WEBJARKIALIIT
ENV DATABASE_USERNAME=WEBJARKIALIIT
ENV DATABASE_PASSWORD=WEBJARKIALIIT
 
ADD target/login-0.0.1-SNAPSHOT.jar app.jar
 
ENTRYPOINT exec java -jar app.jar
